default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rf_development
  #username: rf
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: rf_test

production:
  <<: *default
  database: rf_production
  username: rf
  password: <%= ENV['RF_DATABASE_PASSWORD'] %>